/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:58:40 GMT 2019
 */

package br.com.marmitaria.rest.exception.notFound;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.exception.notFound.RecuperacaoNaoEncontradaException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RecuperacaoNaoEncontradaException_ESTest extends RecuperacaoNaoEncontradaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RecuperacaoNaoEncontradaException recuperacaoNaoEncontradaException0 = new RecuperacaoNaoEncontradaException();
  }
}
